name: Shell Commands

on:
  workflow_dispatch:
    inputs:
      foo:
        description: "テスト用パラメータ"

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "RUN: ${{ github.event.inputs.foo }}"
