name: Shell Commands

on:
  workflow_dispatch:
    inputs:
      foo:
        description: "テスト用パラメータ"

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "RUN: ${{ github.event.inputs.foo }}"
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
