name: Shell Commands
workflow_dispatch:
inputs:
  foo: this is test
  description: "テスト用パラメータ"

jobs:
  printInputs:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "RUN: ${{ github.event.inputs.foo }}"